version: "3.7"
services:
  node:
    container_name: subspace-node
    image: ghcr.io/subspace/node:gemini-3f-2023-sep-05 # thay doi phiên ban snapshot thành ban moi neu có
    volumes:
      - "/root/Subspace-monitor-linux:/var/subspace:rw" #duong dan luu Data
    ports:
      - "0.0.0.0:30333:30333"
      - "0.0.0.0:30433:30433"
    expose:
      - "9615:9615"
    restart: unless-stopped
    command: [
      "--chain", "gemini-3f",
      "--base-path", "/var/subspace",
      "--execution", "wasm",
      "--blocks-pruning", "256",
      "--state-pruning", "archive",
      "--port", "30333",
      "--dsn-listen-on", "/ip4/0.0.0.0/tcp/30433",
      "--rpc-cors", "all",
      "--rpc-methods", "unsafe",
      "--rpc-external",
      "--no-private-ipv4",
      "--prometheus-external",
      "--prometheus-port", "9615",
      "--validator",
      "--name", "nhap ten node cua ban"
    ]
    healthcheck:
      timeout: 5s
      interval: 30s
      retries: 60

  farmer:
    container_name: subspace-farmer
    depends_on:
      node:
        condition: service_healthy
    image: ghcr.io/subspace/farmer:gemini-3f-2023-sep-05 # thay doi phiên ban snapshot thành ban moi neu có
    volumes:       
        - "\root\plot\:/media/subspace-plot:rw" #doi vi tri luu file plot o dây
      #  - "\root\plot1\:/media/subspace-plot1:rw"        
    ports:
        - "0.0.0.0:30533:30533"
    restart: unless-stopped
    command: 
     [
      "farm",       
      "path=/media/subspace-plot,size=100G", #thay doi dung luong can plot       
     # "path=/media/subspace-plot1,size=25G",          
      "--node-rpc-url", "ws://node:9944",
      "--listen-on", "/ip4/0.0.0.0/tcp/30533",
      "--reward-address", "nhap dia chi vi cua ban"      
     ]
     
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=ADMIN #dây là user login vào grafana
      - GF_SECURITY_ADMIN_PASSWORD=MFL123123 # dây là pass login vào grafana
      - GF_USERS_ALLOW_SIGN_UP=false #link truy cap grafana monitor localhost:3000
      - GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION=false
    restart: unless-stopped
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090:9090

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
      
volumes:
  node-data:
  farmer-data:
  grafana_data:
  prometheus_data:
